publish_to: none
name: remvibe_dart_models
description: Shared Dart models used by RemVibe services.
version: 1.0.0
repository: https://github.com/nusretm/remvibe_dart_models

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
